---
- hosts: all
  tasks:
    - name: Deploy unitfile with silpion registry
      become: true
      register: registed_unitfile
      template:
        src: templates/docker.unitfile.j2
        dest: /etc/systemd/system/docker.service

    - name: Reload unitfiles
      become: true
      when: registed_unitfile|changed
      command: systemctl daemon-reload

    - name: Deploy docker repo
      become: true
      template:
        src: templates/docker.repo.j2
        dest: /etc/yum.repos.d/docker.repo

    - name: Install docker
      become: true
      yum:
        state: present
        name: docker-engine

    - name: Enable and start docker
      become: true
      service:
        state: started
        enabled: True
        name: docker

