---
- hosts: all
  tasks:
    - name: Add bashalias
      with_items:
        - 'd=docker'
        - 'l="ls -lh"'
        - 's=systemctl'
      become: true
      lineinfile:
        dest: /root/.bashrc
        state: present
        line: "alias {{ item }}"
    - name: Deploy unitfile with silpion registry
      become: true
      register: registed_unitfile
      template:
        src: templates/docker.unitfile.j2
        dest: /etc/systemd/system/docker.service

    - name: Reload unitfiles
      become: true
      when: registed_unitfile|changed
      command: systemctl daemon-reload

    - name: Deploy docker repo
      become: true
      template:
        src: templates/docker.repo.j2
        dest: /etc/yum.repos.d/docker.repo

    - name: Install docker
      become: true
      yum:
        state: present
        name: docker-engine

    - name: Enable and start docker
      become: true
      service:
        state: started
        enabled: True
        name: docker

    - name: Install docker_service module dependencies
      become: true
      with_items:
        - PyYAML
        - python-docker-py
        - epel-release
      yum:
        state: present
        name: "{{ item }}"

    - name: Install pip - must be run after epel is present
      become: true
      yum:
        state: present
        name: python-pip

    - name: Install docker-compose
      become: true
      pip:
        state: present
        name: docker-compose

    - name: Add consul
      become: true
      docker_service:
        state: present
        project_name: consul
        definition:
          version: "2"
          volumes:
            consul-data: {}
          services:
            consul:
              command: [
                "-bootstrap",
                "-dc",
                "home",
                "-node",
                "consul",
                "-advertise",
                "{{ ansible_default_ipv4.address }}",
                "-advertise-wan",
                "{{ ansible_default_ipv4.address }}",
                "-data-dir",
                "/consul-data",
                "-domain",
                "amasrv.com",
                "-recursor",
                "8.8.8.8"
              ]
              image: docker-registry.office.silpion.de:5000/silpion/consul
              network_mode: host
              restart: always
              volumes:
                - consul-data:/consul-data
    - name: Add Registrator
      become: true
      docker_service:
          state: present
          project_name: registrator
          definition:
            version: "2"
            services:
              registrator:
                command: [
                "-ip={{ ansible_default_ipv4.address }}",
                "consul://{{ ansible_default_ipv4.address }}:8500"
                ]
                image: gliderlabs/registrator:latest
                network_mode: host
                restart: always
                volumes:
                  - '/var/run/docker.sock:/tmp/docker.sock:rw'
